---
language: python
services: docker

env:
  global:
    - ROLE_NAME: glpi
  matrix:
    - MOLECULE_DISTRIB: debian10:latest
      MOLECULE_PLAYBOOK: debian10-playbook.yml

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-$ROLE_NAME supertarto.$ROLE_NAME
  - cd supertarto.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
