---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: supertarto.apache
    - role: supertarto.mariadb
    - role: supertarto.php
    - role: supertarto.glpi
  tasks:
    - name: set php_packages (Debian 10)
      set_fact:
        php_packages:
          - php7.3
          - php7.3-gd
          - php7.3-mysql
          - php7.3-curl
          - php7.3-imap
          - php7.3-json
          - php7.3-ldap
          - php7.3-mbstring
          - php7.3-xml
          - php7.3-cli
          - php7.3-xmlrpc
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'

    - name: set php_packages (Debian 9)
      set_fact:
        php_packages:
          - php7.0
          - php7.0-gd
          - php7.0-mysql
          - php7.0-curl
          - php7.0-imap
          - php7.0-json
          - php7.0-ldap
          - php7.0-mbstring
          - php7.0-xml
          - php7.0-cli
          - php7.0-xmlrpc
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

  vars:
    glpi_db_host: "localhost"
    glpi_db_port: "3306"
    glpi_db_name: "glpi"
    glpi_db_user: "glpi"
    glpi_db_password: "changeit!"
    glpi_lang: "fr_FR"
    apache_create_vhosts: true
    apache_vhosts_filename: "glpi.conf"
    apache_vhost_config:
      - listen_ip: "*"
        listen_port: 80
        server_name: host1
        documentroot: "/var/www/glpi"
        serveradmin: admin@localhost
        custom_param: |
          ProxyRequests Off
          ProxyPreserveHost On
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
          LogLevel warn
        directory:
          - path: "/var/www/glpi"
            config: |
              AllowOverride All
              Order deny,allow
              allow from all

    mariadb_use_dump_script: false
    mariadb_databases:
      - name: "{{ glpi_db_name }}"

    mariadb_users:
      - name: "{{ glpi_db_user }}"
        host: "{{ glpi_db_host }}"
        password: "{{ glpi_db_password }}"
        priv: "{{ glpi_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"
